# Generated by Django 4.2.11 on 2025-10-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="modules/images/"),
        ),
        migrations.AddField(
            model_name="module",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
    ]
